application: zariyaapp1729
version: 1
runtime: php
api_version: 1

handlers:
# sms related files
- url: /
  script: helloworld.php
- url: /default.php
  script: default.php
- url: /incident_options.php
  script: incident_options.php
- url: /location_data.php
  script: location_data.php
- url: /person_details.php
  script: person_details.php
- url: /date_time_details.php
  script: date_time_details.php
- url: /additional_info.php
  script: additional_info.php
- url: /display_data.php
  script: display_data.php

# voice related files
- url: /response_1.php
  script: response_1.php
- url: /phonehome.*
  script: phonehome.php  
- url: /phone_report_1.*
  script: phone_report_1.php  
- url: /phone_report_2.*
  script: phone_report_2.php  
- url: /phone_report_3.*
  script: phone_report_3.php 
- url: /phone_report_4.*
  script: phone_report_4.php   
- url: /phone_report_5.*
  script: phone_report_5.php
- url: /phone_report_6.*
  script: phone_report_6.php      
- url: /phone_report_7.*
  script: phone_report_7.php   
- url: /phone_report_8.*
  script: phone_report_8.php   

- url: /sms-test.*
  script: sms-test.php
- url: /post_example.*
  script: post_example.php
- url: /bad_words.*
  script: index.html
- url: /sms-reply.*
  script: sms-reply.php
- url: /twiliosmsreply.*
  script: twilio_sms_reply.php
- url: /test_form
  script: test_form.php
- url: /send_sms.*
  script: send_sms.php

