application: zariyaapp1729
version: 1
runtime: php
api_version: 1

handlers:
- url: /
  script: helloworld.php
- url: /default.*
  script: default.php
- url: /redirect_0.*
  script: redirect_0.php
- url: /index\.html
  script: test123.php
- url: /smstest
  script: smstest.php
<<<<<<< HEAD
- url: /response_1.php
  script: response_1.php
- url: /phonehome.*
  script: phonehome.php  
- url: /phone_report_1.*
  script: phone_report_1.php  
- url: /phone_report_2.*
  script: phone_report_2.php  
- url: /phone_report_3.*
  script: phone_report_3.php 
=======
- url: /sms-test.*
  script: sms-test.php
- url: /post_example.*
  script: post_example.php
- url: /bad_words.*
  script: index.html
- url: /sms-reply.*
  script: sms-reply.php
- url: /twiliosmsreply.*
  script: twilio_sms_reply.php
- url: /test_form
  script: test_form.php
- url: /send_sms.*
  script: send_sms.php

>>>>>>> efb31c7102d916e72155445e8d07e899a38bab37
